// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPUssZTwytD-dmR9L4QmQqhvyjJS6VQtc',
    appId: '1:86054517174:web:3e8f1ceb0d183a65e9a917',
    messagingSenderId: '86054517174',
    projectId: 'mobap-c6b11',
    authDomain: 'mobap-c6b11.firebaseapp.com',
    storageBucket: 'mobap-c6b11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGaF5NapEbmAdtvUHuzVeuM31KGtIY4hE',
    appId: '1:86054517174:android:3da1715af21bc9c0e9a917',
    messagingSenderId: '86054517174',
    projectId: 'mobap-c6b11',
    storageBucket: 'mobap-c6b11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTErwdzUxfuJ9CvIyBSNx1COVdezd8mtg',
    appId: '1:86054517174:ios:369eb529bb16c880e9a917',
    messagingSenderId: '86054517174',
    projectId: 'mobap-c6b11',
    storageBucket: 'mobap-c6b11.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTErwdzUxfuJ9CvIyBSNx1COVdezd8mtg',
    appId: '1:86054517174:ios:369eb529bb16c880e9a917',
    messagingSenderId: '86054517174',
    projectId: 'mobap-c6b11',
    storageBucket: 'mobap-c6b11.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPUssZTwytD-dmR9L4QmQqhvyjJS6VQtc',
    appId: '1:86054517174:web:77410c86f464f7b5e9a917',
    messagingSenderId: '86054517174',
    projectId: 'mobap-c6b11',
    authDomain: 'mobap-c6b11.firebaseapp.com',
    storageBucket: 'mobap-c6b11.firebasestorage.app',
  );

}